# -*- coding: utf-8 -*-
"""web_scraping_with_beautifulSoup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mhc3uVCM04m1dAx_MG8gIAUYmT8mrPKX

#Web Scraping using Python with Beautiful Soup

##Installing the libraries
"""

!pip install beautifulsoup4
!pip install lxml
!pip install requests

"""##Importin libraries"""

from bs4 import BeautifulSoup
import requests
import csv

oursource = requests.get('https://www.worldometers.info/coronavirus/').text

csv_file = open('corona_data.csv', 'w')

csv_writer = csv.writer(csv_file)

csv_writer.writerow(['Number','Country Name','Total Cases', 'New Cases','Total Deaths','New Deaths','Total Recovered','New Recovered'])

soup = BeautifulSoup(oursource,'lxml')

ourBody = soup.find('table', id = 'main_table_countries_today')
body = ourBody.tbody

for table in body.find_all('tr'):
  var = []
  for countryData in table.find_all('td'):
    var.append(countryData.text)
    print(countryData.text)
  csv_writer.writerow([var[0],var[1],var[2], var[3],var[4],var[5],var[6],var[7]])

